server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cadastro_banda
    username: root
    password: jjnic@j0n
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

